### ISSUE TITLE
creare una tabella in Markdown da file csv

### ISSUE THREAD

**Issue by pigreco** [pigreco/shortest_line#1]
@aborruso

```
|id|wkt_short|
|---|---|
|1|LineString (2374721.34451647 4221173.95495503, 2374747.12450154 4221073.54869737)|
|2|LineString (2375057.90261554 4220845.93893969, 2374983.85597884 4221134.3311037)|
|3|LineString (2375216.78537297 4221255.95895887, 2375105.47321592 4221305.36488953)|
|4|LineString (2375466.21421797 4221809.48598475, 2375657.31309225 4221534.57181474)|
|5|LineString (2375734.43564718 4221049.24053253, 2375575.50287336 4221477.70373576)|
```

**Comment by aborruso** [comment]
@pigreco ma è corretto e funziona

| id | wkt_short |
| --- | --- |
| 1 | LineString (2374721.34451647 4221173.95495503, 2374747.12450154 4221073.54869737) |
| 2 | LineString (2375057.90261554 4220845.93893969, 2374983.85597884 4221134.3311037) |
| 3 | LineString (2375216.78537297 4221255.95895887, 2375105.47321592 4221305.36488953) |
| 4 | LineString (2375466.21421797 4221809.48598475, 2375657.31309225 4221534.57181474) |
| 5 | LineString (2375734.43564718 4221049.24053253, 2375575.50287336 4221477.70373576) |
